package terraform.backend.services;

import org.springframework.stereotype.Service;
import terraform.backend.models.ObjectSelection;
import terraform.backend.models.TransportArtefact;

import java.io.IOException;
import java.nio.file.*;
import java.util.*;

@Service
public class WizardService {

    private String workspace;
    private String environment;

    private List<ObjectSelection> selections = new ArrayList<>();
    private final List<String> logs = new ArrayList<>();

    private final Map<String, String> generatedFiles = new HashMap<>();

    // -----------------------------
    // Canonical type mapping (STANDARD objects)
    // -----------------------------

    private static final Map<String, String> TYPE_MAP = Map.ofEntries(
            Map.entry("entitlement", "entitlements"),
            Map.entry("entitlements", "entitlements"),

            Map.entry("account", "accounts"),
            Map.entry("accounts", "accounts"),

            Map.entry("role", "roles"),
            Map.entry("roles", "roles"),

            Map.entry("endpoint", "endpoints"),
            Map.entry("endpoints", "endpoints"),

            Map.entry("usergroup", "user_groups"),
            Map.entry("usergroups", "user_groups"),

            Map.entry("application", "applications"),
            Map.entry("applications", "applications"),

            Map.entry("securitysystem", "security_systems"),
            Map.entry("securitysystems", "security_systems"),

            Map.entry("schedulejob", "schedule_jobs"),
            Map.entry("schedulejobs", "schedule_jobs")
    );

    // -----------------------------
    // Template engine
    // -----------------------------

    private String render(String template, Map<String, String> vars) {
        String result = template;
        for (var e : vars.entrySet()) {
            result = result.replace("{{" + e.getKey() + "}}", e.getValue());
        }
        return result;
    }

    // -----------------------------
    // Attribute rendering (STANDARD)
    // -----------------------------

    private String renderAttributes(Map<String, String> attrs) {
        if (attrs == null || attrs.isEmpty()) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        for (var e : attrs.entrySet()) {
            sb.append("  ")
              .append(e.getKey())
              .append(" = \"")
              .append(e.getValue())
              .append("\"\n");
        }
        return sb.toString();
    }

    // -----------------------------
    // STANDARD object templates
    // -----------------------------

    private static final String ACCOUNT_TEMPLATE =
            """
            resource "saviynt_account" "{{res}}" {
              account_name = "{{res}}"
              description  = "Generated by Saviynt Terraform Wizard"

{{attributes}}
              # Optional attributes
              # status      = "Active"
              # endpointkey = 123
            }
            """;

    private static final String ENTITLEMENT_TEMPLATE =
            """
            resource "saviynt_entitlement" "{{res}}" {
              entitlement_name  = "{{res}}"
              entitlement_value = "{{res}}"

{{attributes}}
              # Optional attributes
              # entitlementtype = "Group"
              # endpointkey     = 123
            }
            """;

    private static final String ROLE_TEMPLATE =
            """
            resource "saviynt_role" "{{res}}" {
              role_name   = "{{res}}"
              description = "Generated by Saviynt Terraform Wizard"

{{attributes}}
              # Optional attributes
              # roletype = "Business"
            }
            """;

    private static final String ENDPOINT_TEMPLATE =
            """
            resource "saviynt_endpoint" "{{res}}" {
              endpoint_name = "{{res}}"
              description   = "Generated by Saviynt Terraform Wizard"

{{attributes}}
              # Optional attributes
              # securitysystem = "ActiveDirectory"
              # endpointtype   = "Application"
            }
            """;

    private static final String APPLICATION_TEMPLATE =
            """
            resource "saviynt_application" "{{res}}" {
              application_name = "{{res}}"
              description      = "Generated by Saviynt Terraform Wizard"

{{attributes}}
              # Optional attributes
              # owner = "admin@example.com"
            }
            """;

    private static final String USERGROUP_TEMPLATE =
            """
            resource "saviynt_user_group" "{{res}}" {
              group_name  = "{{res}}"
              description = "Generated by Saviynt Terraform Wizard"

{{attributes}}
              # Optional attributes
              # status = "Active"
            }
            """;

    private static final String SECURITY_SYSTEM_TEMPLATE =
            """
            resource "saviynt_security_system" "{{res}}" {
              name        = "{{res}}"
              description = "Generated by Saviynt Terraform Wizard"

{{attributes}}
            }
            """;

    private static final String SCHEDULE_JOB_TEMPLATE =
            """
            resource "saviynt_schedule_job" "{{res}}" {
              name        = "{{res}}"
              description = "Generated by Saviynt Terraform Wizard"

{{attributes}}
            }
            """;

    // -----------------------------
    // IMPORT templates (ZIP-based)
    // -----------------------------

    private static final String EMAIL_TEMPLATE_IMPORT =
            """
            resource "saviynt_email_template" "{{name}}" {
              name = "{{name}}"
              file = "${path.module}/../../supporting_files/{{zip}}"
            }
            """;

    private static final String ANALYTICS_IMPORT =
            """
            resource "saviynt_analytics" "{{name}}" {
              name = "{{name}}"
              file = "${path.module}/../../supporting_files/{{zip}}"
            }
            """;

    private static final String SAV_ROLE_IMPORT =
            """
            resource "saviynt_sav_role" "{{name}}" {
              name = "{{name}}"
              file = "${path.module}/../../supporting_files/{{zip}}"
            }
            """;

    private static final String TECHNICAL_RULE_IMPORT =
            """
            resource "saviynt_technical_rule" "{{name}}" {
              name = "{{name}}"
              file = "${path.module}/../../supporting_files/{{zip}}"
            }
            """;

    // -----------------------------
    // EXPORT templates (data source + local_file)
    // -----------------------------

    private static final String EMAIL_TEMPLATE_EXPORT =
            """
            data "saviynt_email_template" "{{name}}" {
              name = "{{name}}"
            }

            resource "local_file" "{{name}}_zip" {
              content  = data.saviynt_email_template.{{name}}.file
              filename = "${path.module}/supporting_files/{{zip}}"
            }
            """;

    private static final String ANALYTICS_EXPORT =
            """
            data "saviynt_analytics" "{{name}}" {
              name = "{{name}}"
            }

            resource "local_file" "{{name}}_zip" {
              content  = data.saviynt_analytics.{{name}}.file
              filename = "${path.module}/supporting_files/{{zip}}"
            }
            """;

    private static final String SAV_ROLE_EXPORT =
            """
            data "saviynt_sav_role" "{{name}}" {
              name = "{{name}}"
            }

            resource "local_file" "{{name}}_zip" {
              content  = data.saviynt_sav_role.{{name}}.file
              filename = "${path.module}/supporting_files/{{zip}}"
            }
            """;

    private static final String TECHNICAL_RULE_EXPORT =
            """
            data "saviynt_technical_rule" "{{name}}" {
              name = "{{name}}"
            }

            resource "local_file" "{{name}}_zip" {
              content  = data.saviynt_technical_rule.{{name}}.file
              filename = "${path.module}/supporting_files/{{zip}}"
            }
            """;

    // -----------------------------
    // Normalization for STANDARD objects
    // -----------------------------

    private String normalize(String type) {
        String key = type.trim().toLowerCase().replace(" ", "").replace("_", "").replace("-", "");
        return TYPE_MAP.getOrDefault(key, key);
    }

    // -----------------------------
    // STANDARD resource generation
    // -----------------------------

    private String generateStandardResource(String type, String name, Map<String, String> attrs) {
        String key = normalize(type);
        String attributesBlock = renderAttributes(attrs);

        Map<String, String> vars = new HashMap<>();
        vars.put("res", name);
        vars.put("attributes", attributesBlock);

        return switch (key) {
            case "accounts" -> render(ACCOUNT_TEMPLATE, vars);
            case "entitlements" -> render(ENTITLEMENT_TEMPLATE, vars);
            case "roles" -> render(ROLE_TEMPLATE, vars);
            case "endpoints" -> render(ENDPOINT_TEMPLATE, vars);
            case "applications" -> render(APPLICATION_TEMPLATE, vars);
            case "user_groups" -> render(USERGROUP_TEMPLATE, vars);
            case "security_systems" -> render(SECURITY_SYSTEM_TEMPLATE, vars);
            case "schedule_jobs" -> render(SCHEDULE_JOB_TEMPLATE, vars);
            default -> "// Unsupported STANDARD object type: " + type;
        };
    }

    // -----------------------------
    // IMPORT resource generation (ZIP-based)
    // -----------------------------

    private String generateImportResource(String type, String name, String zipFileName) {
        String key = type.trim().toLowerCase();

        Map<String, String> vars = new HashMap<>();
        vars.put("name", name);
        vars.put("zip", zipFileName);

        return switch (key) {
            case "emailtemplate", "email_template" -> render(EMAIL_TEMPLATE_IMPORT, vars);
            case "analytics" -> render(ANALYTICS_IMPORT, vars);
            case "savrole", "sav_role" -> render(SAV_ROLE_IMPORT, vars);
            case "technicalrule", "technical_rule" -> render(TECHNICAL_RULE_IMPORT, vars);
            default -> "// Unsupported IMPORT object type: " + type;
        };
    }

    // -----------------------------
    // EXPORT resource generation (data source + local_file)
    // -----------------------------

    private String generateExportResource(String type, String name, String zipFileName) {
        String key = type.trim().toLowerCase();

        Map<String, String> vars = new HashMap<>();
        vars.put("name", name);
        vars.put("zip", zipFileName);

        return switch (key) {
            case "emailtemplate", "email_template" -> render(EMAIL_TEMPLATE_EXPORT, vars);
            case "analytics" -> render(ANALYTICS_EXPORT, vars);
            case "savrole", "sav_role" -> render(SAV_ROLE_EXPORT, vars);
            case "technicalrule", "technical_rule" -> render(TECHNICAL_RULE_EXPORT, vars);
            default -> "// Unsupported EXPORT object type: " + type;
        };
    }

    // -----------------------------
    // Module variables.tf
    // -----------------------------

    private String moduleVariablesTf() {
        return """
            variable "environment" {
              type = string
            }

            variable "workspace_name" {
              type = string
            }

            variable "module_enabled" {
              type    = bool
              default = true
            }
            """;
    }

    // -----------------------------
    // Module outputs.tf
    // -----------------------------

    private String moduleOutputsTf() {
        return """
            output "resource_ids" {
              value = []
            }
            """;
    }

    // -----------------------------
    // Module providers.tf
    // -----------------------------

    private String moduleProvidersTf() {
        return """
            terraform {
              required_providers {
                saviynt = {
                  source  = "saviynt/saviynt"
                  version = ">= 1.0.0"
                }
              }
            }
            """;
    }

    // -----------------------------
    // Root variables.tf
    // -----------------------------

    private String rootVariablesTf() {
        return """
            variable "environment" {
              type = string
            }

            variable "workspace_name" {
              type = string
            }

            variable "saviynt_url" {
              type = string
            }

            variable "saviynt_username" {
              type = string
            }

            variable "saviynt_password" {
              type      = string
              sensitive = true
            }
            """;
    }

    // -----------------------------
    // Root outputs.tf
    // -----------------------------

    private String rootOutputsTf() {
        return """
            output "all_modules" {
              value = "Saviynt Terraform modules generated successfully"
            }
            """;
    }

    // -----------------------------
    // Root provider.tf
    // -----------------------------

    private String rootProviderTf() {
        return """
            terraform {
              required_providers {
                saviynt = {
                  source  = "saviynt/saviynt"
                  version = ">= 1.0.0"
                }
              }
            }

            provider "saviynt" {
              url      = var.saviynt_url
              username = var.saviynt_username
              password = var.saviynt_password
            }
            """;
    }

    // -----------------------------
    // TRANSPORT processing (batch of IMPORTs)
    // -----------------------------

    private void processTransport(ObjectSelection sel) {
        if (sel.getArtefacts() == null || sel.getArtefacts().isEmpty()) {
            logs.add("Transport selection has no artefacts.");
            return;
        }

        for (TransportArtefact art : sel.getArtefacts()) {
            String type = art.getType();
            String name = art.getName();
            String zip = art.getZipFileName(); // e.g. "WelcomeTemplate.zip"

            String normalizedType = type.trim().toLowerCase();
            String moduleName = "saviynt_transport_" + normalizedType;
            String modulePath = "modules/" + moduleName + "/";

            String tfContent = generateImportResource(type, name, zip);
            generatedFiles.put(modulePath + name + ".tf", tfContent);

            generatedFiles.putIfAbsent(modulePath + "variables.tf", moduleVariablesTf());
            generatedFiles.putIfAbsent(modulePath + "outputs.tf", moduleOutputsTf());
            generatedFiles.putIfAbsent(modulePath + "providers.tf", moduleProvidersTf());

            logs.add("Transport artefact processed: type=" + type + ", name=" + name + ", zip=" + zip);
        }
    }

    // -----------------------------
    // Main generation logic
    // -----------------------------

    public void generate() {
        logs.add("Starting Terraform generation...");

        generatedFiles.clear();

        // Root-level files
        generatedFiles.put("variables.tf", rootVariablesTf());
        generatedFiles.put("outputs.tf", rootOutputsTf());
        generatedFiles.put("provider.tf", rootProviderTf());

        // Build main.tf
        StringBuilder mainTf = new StringBuilder();

        // STANDARD / EXPORT / IMPORT modules
        for (ObjectSelection sel : selections) {
            String op = sel.getOperation() == null ? "STANDARD" : sel.getOperation().toUpperCase();
            if ("TRANSPORT".equals(op)) {
                continue;
            }

            String type = sel.getType();
            String normalized = normalize(type);
            String moduleName = "saviynt_" + normalized;

            mainTf.append("""
                module "%s" {
                  source = "./modules/%s"

                  environment    = var.environment
                  workspace_name = var.workspace_name
                  module_enabled = true

                  providers = {
                    saviynt = saviynt
                  }
                }

                """.formatted(moduleName, moduleName));
        }

        // TRANSPORT modules
        for (ObjectSelection sel : selections) {
            String op = sel.getOperation() == null ? "STANDARD" : sel.getOperation().toUpperCase();
            if (!"TRANSPORT".equals(op)) continue;
            if (sel.getArtefacts() == null) continue;

            for (TransportArtefact art : sel.getArtefacts()) {
                String type = art.getType();
                String normalizedType = type.trim().toLowerCase();
                String moduleName = "saviynt_transport_" + normalizedType;

                mainTf.append("""
                    module "%s" {
                      source = "./modules/%s"

                      environment    = var.environment
                      workspace_name = var.workspace_name
                      module_enabled = true

                      providers = {
                        saviynt = saviynt
                      }
                    }

                    """.formatted(moduleName, moduleName));
            }
        }

        generatedFiles.put("main.tf", mainTf.toString());

        // Generate module files for STANDARD / EXPORT / IMPORT
        for (ObjectSelection sel : selections) {
            String op = sel.getOperation() == null ? "STANDARD" : sel.getOperation().toUpperCase();

            if ("TRANSPORT".equals(op)) {
                processTransport(sel);
                continue;
            }

            String type = sel.getType();
            String name = sel.getName();
            Map<String, String> attrs = sel.getAttributes();

            String normalized = normalize(type);
            String moduleName = "saviynt_" + normalized;
            String modulePath = "modules/" + moduleName + "/";

            generatedFiles.putIfAbsent(modulePath + "variables.tf", moduleVariablesTf());
            generatedFiles.putIfAbsent(modulePath + "outputs.tf", moduleOutputsTf());
            generatedFiles.putIfAbsent(modulePath + "providers.tf", moduleProvidersTf());

            String tfContent;
            switch (op) {
    case "EXPORT":
        String zipNameExport = name + ".zip";
        tfContent = generateExportResource(type, name, zipNameExport);
        break;

    case "IMPORT":
        String zipNameImport = sel.getZipFileName() != null
                ? sel.getZipFileName()
                : name + ".zip";
        tfContent = generateImportResource(type, name, zipNameImport);
        break;

    case "STANDARD":
    default:
        tfContent = generateStandardResource(type, name, attrs);
        break;
}

            generatedFiles.put(modulePath + name + ".tf", tfContent);
            logs.add("Generated module: " + moduleName + " with resource " + name + " (op=" + op + ")");
        }

        logs.add("Terraform files generated in memory.");

        try {
            writeToWorkspace();
            logs.add("Files written to workspace: " + workspace);
        } catch (IOException e) {
            logs.add("ERROR writing to workspace: " + e.getMessage());
            throw new RuntimeException(e);
        }

        logs.add("Generation complete.");
    }

    // -----------------------------
    // Write files to workspace
    // -----------------------------

    private void writeToWorkspace() throws IOException {
        Path workspacePath = Paths.get(workspace);

        if (!Files.exists(workspacePath)) {
            Files.createDirectories(workspacePath);
            logs.add("Workspace folder created: " + workspacePath);
        }

        for (var entry : generatedFiles.entrySet()) {
            Path filePath = workspacePath.resolve(entry.getKey());
            Files.createDirectories(filePath.getParent());
            Files.writeString(filePath, entry.getValue(),
                    StandardOpenOption.CREATE,
                    StandardOpenOption.TRUNCATE_EXISTING);
        }
    }

    // -----------------------------
    // Setters
    // -----------------------------

    public void setWorkspace(String workspace) {
        this.workspace = workspace;
        logs.add("Workspace set to: " + workspace);
    }

    public void setEnvironment(String environment) {
        this.environment = environment;
        logs.add("Environment set to: " + environment);
    }

    public void setSelections(List<ObjectSelection> selections) {
        this.selections = selections;
        logs.add("RAW selections received: " + selections.size());
    }

    // -----------------------------
    // Getters
    // -----------------------------

    public Map<String, String> getGeneratedFiles() {
        return generatedFiles;
    }

    public List<String> getLogs() {
        return logs;
    }
}
