"use client";

import Link from "next/link";
import { useState, useEffect } from "react";

interface DashboardTile {
  title: string;
  description: string;
  icon: string;
  href: string;
  badge?: string;
  color: string;
}

export default function KnowMoreDashboard() {
  const [viewMode, setViewMode] = useState<"desktop" | "mobile">("desktop");

  useEffect(() => {
    if (typeof window !== "undefined") {
      const saved = sessionStorage.getItem("envizor_view_mode") as any;
      const isMobile = window.innerWidth < 768;
      setViewMode(saved === "mobile" || saved === "desktop" ? saved : (isMobile ? "mobile" : "desktop"));

      const handleViewModeChange = (e: Event) => {
        const detail = (e as CustomEvent).detail;
        if (detail === "desktop" || detail === "mobile") {
          setViewMode(detail);
        }
      };
      window.addEventListener("envizorViewModeChange", handleViewModeChange);
      return () => window.removeEventListener("envizorViewModeChange", handleViewModeChange);
    }
  }, []);

  const tiles: DashboardTile[] = [
    {
      title: "🚀 Mission & Purpose",
      description: "Understand the core reasons behind Envizor, bridging the gap between cloud portals and Infrastructure-as-Code.",
      icon: "🚀",
      href: "/wizard/know-more/mission",
      color: "var(--accent)"
    },
    {
      title: "📈 Process Walkthrough",
      description: "A detailed breakdown of how raw API discovery feeds the drift reconciler, compiles HCL, and deploys.",
      icon: "📈",
      href: "/wizard/know-more/process",
      color: "var(--accent)"
    },
    {
      title: "⚠️ Manual vs. Envizor",
      description: "Run the interactive drift sandbox simulator and compare visual administration vs. Git-audited automation.",
      icon: "🎮",
      href: "/wizard/know-more/vs-manual",
      badge: "Interactive Sim",
      color: "var(--warning)"
    },
    {
      title: "🛡️ Key Capabilities",
      description: "Explore Envizor's drift crawler, selective workspace sync, schema registry, and automatic archiving systems.",
      icon: "🛡️",
      href: "/wizard/know-more/capabilities",
      color: "var(--accent)"
    },
    {
      title: "🔧 Terraform Provider",
      description: "Browse EIC resources, dynamic attributes, provider configurations, and autogenerated HCL blueprints.",
      icon: "🔧",
      href: "/wizard/know-more/terraform",
      color: "#a78bfa"
    },
    {
      title: "🔌 Disconnected Apps",
      description: "Onboard air-gapped legacy networks using autonomous scraping agents and test active ticket API consoles.",
      icon: "🔌",
      href: "/wizard/know-more/disconnected-onboarding",
      badge: "API Console",
      color: "#fb923c"
    },
    {
      title: "🤖 Agent GitOps CD",
      description: "Dive into automated Git branch releases, Terrafrom plan inspectors, and continuous delivery pipelines.",
      icon: "🤖",
      href: "/wizard/know-more/agent-deployment",
      color: "#ec4899"
    },
    {
      title: "❓ Frequently Asked FAQs",
      description: "Find instant answers to common questions about security compliance, drift detection, and provider limits.",
      icon: "❓",
      href: "/wizard/know-more/faq",
      color: "var(--text-secondary)"
    }
  ];

  return (
    <div
      className={`min-h-screen w-full flex flex-col items-center px-4 md:px-6 py-12 relative overflow-hidden transition-all duration-300 ${
        viewMode === "mobile" ? "view-mode-mobile" : "view-mode-desktop"
      }`}
      style={{ background: "var(--bg-base)", color: "var(--text-primary)" }}
    >
      {/* Background Graphic Accents */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden">
        <div
          className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[700px] h-[700px] rounded-full blur-3xl opacity-10 pointer-events-none"
          style={{ background: "var(--accent)" }}
        />
      </div>

      <div className="max-w-6xl w-full flex flex-col gap-8 relative z-10">
        
        {/* Back navigation header */}
        <div className="flex justify-between items-center">
          <Link
            href="/wizard/steps/welcome"
            className="flex items-center gap-2 text-sm font-semibold transition hover:underline"
            style={{ color: "var(--accent)" }}
          >
            <span>←</span> Back to Envizor Hub
          </Link>
          <div className="flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse" />
            <span className="text-xs font-bold text-emerald-400 uppercase tracking-wider">Ecosystem Guide</span>
          </div>
        </div>

        {/* Hero title block */}
        <div className="text-center max-w-3xl mx-auto flex flex-col items-center gap-3">
          <div
            className="w-12 h-12 rounded-2xl flex items-center justify-center mb-2 shadow-lg"
            style={{
              background: "linear-gradient(135deg, var(--accent), var(--accent-hover))",
              boxShadow: "0 4px 20px var(--accent-glow)"
            }}
          >
            <span className="text-2xl text-white">⚙️</span>
          </div>
          <h1 className="text-4xl font-black tracking-tight" style={{ color: "var(--text-primary)" }}>
            Discover Envizor Orchestration
          </h1>
          <p className="text-sm leading-relaxed" style={{ color: "var(--text-secondary)" }}>
            Select a guide below to explore the core pillars, interactive sandboxes, and documentation blueprints that power GitOps Identity Governance-as-Code.
          </p>
        </div>

        {/* Grid of Dashboard Tiles */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 pt-4">
          {tiles.map((tile) => (
            <Link
              key={tile.title}
              href={tile.href}
              className="group relative rounded-2xl border p-6 flex flex-col justify-between transition-all duration-300 hover:scale-[1.02] hover:shadow-xl hover:border-slate-400/35 text-left"
              style={{
                backgroundColor: "var(--bg-surface)",
                borderColor: "var(--border)",
                boxShadow: "0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -1px rgba(0,0,0,0.06)"
              }}
            >
              {/* Highlight Hover Bar */}
              <div 
                className="absolute top-0 left-0 right-0 h-1.5 rounded-t-2xl transition-opacity duration-300 opacity-70 group-hover:opacity-100" 
                style={{ background: tile.color }}
              />

              <div className="space-y-4">
                <div className="flex justify-between items-center">
                  <span className="text-3xl">{tile.icon}</span>
                  {tile.badge && (
                    <span 
                      className="px-2 py-0.5 rounded-full text-[9px] font-black uppercase tracking-wider border"
                      style={{ 
                        borderColor: `${tile.color}35`, 
                        color: tile.color, 
                        backgroundColor: `${tile.color}08` 
                      }}
                    >
                      {tile.badge}
                    </span>
                  )}
                </div>

                <div className="space-y-1">
                  <h3 className="text-sm font-bold text-slate-100 group-hover:text-white transition-colors">
                    {tile.title}
                  </h3>
                  <p className="text-[11.5px] leading-relaxed text-slate-400 group-hover:text-slate-350 transition-colors">
                    {tile.description}
                  </p>
                </div>
              </div>

              <div className="flex justify-end pt-4">
                <span className="text-xs font-bold transition-transform duration-300 group-hover:translate-x-1" style={{ color: tile.color }}>
                  Read Guide &rarr;
                </span>
              </div>
            </Link>
          ))}
        </div>

        {/* Info Callout */}
        <div 
          className="rounded-2xl p-6 border text-center flex flex-col md:flex-row items-center justify-between gap-4 animate-fadeIn"
          style={{ 
            background: "linear-gradient(135deg, rgba(6, 182, 212, 0.05), rgba(99, 102, 241, 0.05))",
            borderColor: "var(--border)" 
          }}
        >
          <div className="text-left">
            <h4 className="text-sm font-extrabold" style={{ color: "var(--text-primary)" }}>
              Ready to configure your environments?
            </h4>
            <p className="text-xs text-slate-400 mt-1">
              Onboard Day 0 setups or compile infrastructure configurations straight from the DevOps Console.
            </p>
          </div>
          <div className="flex gap-3">
            <Link 
              href="/wizard/day0-setup" 
              className="py-2.5 px-4 rounded-xl text-xs font-bold transition-all shadow-sm border border-slate-700 bg-slate-900 text-slate-200 hover:bg-slate-800"
            >
              Day 0 Setup
            </Link>
            <Link 
              href="/wizard/home" 
              className="py-2.5 px-4 rounded-xl text-xs font-bold transition-all text-white shadow-md"
              style={{
                background: "linear-gradient(135deg, var(--accent), var(--accent-hover))",
                boxShadow: "0 4px 14px var(--accent-glow)"
              }}
            >
              Launch DevOps Wizard
            </Link>
          </div>
        </div>

      </div>
    </div>
  );
}
